//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AcademicRank
{
	private MultilingualString title
	{
		get;
		set;
	}

	private int rank
	{
		get;
		set;
	}

	private MultilingualString shortTitle
	{
		get;
		set;
	}

}

