//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AnnualEntitlementWithCarriedOver
{
	private object leaveDays
	{
		get;
		set;
	}

	private object carriedOverLeaveDays
	{
		get;
		set;
	}

	private object monthOfServiceLowerBound
	{
		get;
		set;
	}

	private object monthOfServiceUpperBound
	{
		get;
		set;
	}

	public virtual MultiTierAnnualEntitlementWithCarriedOver MultiTierAnnualEntitlementWithCarriedOver
	{
		get;
		set;
	}

}

