//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Eligibility
{
	private string gender
	{
		get;
		set;
	}

	private object religion
	{
		get;
		set;
	}

	private object lengthOfService
	{
		get;
		set;
	}

	private object marriage
	{
		get;
		set;
	}

	private bool IsEligible()
	{
		throw new System.NotImplementedException();
	}

}

