//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LeaveRequest
{
	private object requestFrom
	{
		get;
		set;
	}

	private object erquestTo
	{
		get;
		set;
	}

	public virtual LeaveBenefit LeaveBenefit
	{
		get;
		set;
	}

	public virtual IEnumerable<LeaveRequestStat> LeaveRequestStat
	{
		get;
		set;
	}

	public virtual LeaveRequestStat States
	{
		get;
		set;
	}

	public virtual void Submit()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Approve()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Reject()
	{
		throw new System.NotImplementedException();
	}

}

