//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class LeaveState
{
	public virtual LeaveState Approva()
	{
		throw new System.NotImplementedException();
	}

	public virtual LeaveState Reject()
	{
		throw new System.NotImplementedException();
	}

}

