//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LeaveRequest
{
	private TimeInterval leavePeriod
	{
		get;
		set;
	}

	public virtual LeaveBenefit LeaveBenefit
	{
		get;
		set;
	}

	public virtual Personnel employee
	{
		get;
		set;
	}

}

