//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Language Code
///   th-TH
///   en-US
/// </remarks>
public class MLSValue
{
	private object languageCode
	{
		get;
		set;
	}

	private object stringValue
	{
		get;
		set;
	}

	public virtual MultilingualString MultilingualString
	{
		get;
		set;
	}

}

