//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MultilingualString
{
	public virtual IEnumerable<MLSValue> MLSValue
	{
		get;
		set;
	}

	public virtual string GetValue(string langguageCode)
	{
		throw new System.NotImplementedException();
	}

}

