//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
	public virtual IEnumerable<Marriage> Marriage
	{
		get;
		set;
	}

	public virtual IEnumerable<PersonAcademicRank> PersonAcademicRank
	{
		get;
		set;
	}

	public virtual PersonAcademicRank CurrentAcademicRank
	{
		get;
		set;
	}

	public virtual IEnumerable<PersonName> PersonName
	{
		get;
		set;
	}

}

