//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PersonnelLeaveBenefitAnnualSummary
{
	private int leaveYear
	{
		get;
		set;
	}

	private int entitledLeaveDays
	{
		get;
		set;
	}

	private int requestingLeaveDayes
	{
		get;
		set;
	}

	private int approvedLeaveDays
	{
		get;
		set;
	}

	private object carriedOverLeaveDays
	{
		get;
		set;
	}

	public virtual LeaveBenefit LeaveBenefit
	{
		get;
		set;
	}

	public virtual Personnel personnel
	{
		get;
		set;
	}

}

