//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PersonAcademicRank
{
	private TimeInterval effectivePeriod
	{
		get;
		set;
	}

	public virtual AcademicRank AcademicRank
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

}

