//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PersonName
{
	private string title
	{
		get;
		set;
	}

	private MultilingualString firstName
	{
		get;
		set;
	}

	private MultilingualString middleName
	{
		get;
		set;
	}

	private MultilingualString lastName
	{
		get;
		set;
	}

	public virtual Person Person
	{
		get;
		set;
	}

}

